### ISSUE TITLE
Missing ``utils'' package

### ISSUE THREAD

**Issue by yechao-zhang** [Haochen-Luo/CroPA#1]
Traceback (most recent call last):
  File "/home/user/CroPA/main.py", line 14, in <module>
    from utils.attack_tool import (
ModuleNotFoundError: No module named 'utils'

**Comment by Haochen-Luo** [comment]
Hi yechao

Thanks for pointing this out. 

The code and data are stored on a remote server but I lost access to this server.  I am trying to recover the code and thanks for your patience.
