### ISSUE TITLE
Missing the file

### ISSUE THREAD

**Issue by AI4Math-ShanZhang** [Haochen-Luo/CroPA#3]
Hi, dear authors: 

Thank you for releasing the code and contributing to the community. However, when I run the code, I can't find the id_to_question.json, data/img_specific_questions.json and data/clean_train_vqa_map.json.

**Comment by Haochen-Luo** [comment]
Hi, 
I uploaded the files a couple of weeks ago and this issue is resolved.

**Comment by ranck626** [comment]
still no img_specific_questions.json
